/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/_onboarding/route'
import { Route as OnboardingIndexImport } from './routes/_onboarding/index'
import { Route as OnboardingWorkoutImport } from './routes/_onboarding/workout'
import { Route as OnboardingWeightSelectImport } from './routes/_onboarding/weight-select'
import { Route as OnboardingTimeSelectorImport } from './routes/_onboarding/time-selector'
import { Route as OnboardingStrengthEquipmentImport } from './routes/_onboarding/strength-equipment'
import { Route as OnboardingSettingsImport } from './routes/_onboarding/settings'
import { Route as OnboardingNotificationsImport } from './routes/_onboarding/notifications'
import { Route as OnboardingGoalsImport } from './routes/_onboarding/goals'
import { Route as OnboardingGenderSelectImport } from './routes/_onboarding/gender-select'
import { Route as OnboardingFitnessSelectImport } from './routes/_onboarding/fitness-select'
import { Route as OnboardingDayTimeImport } from './routes/_onboarding/day-time'
import { Route as OnboardingCardioEquipmentImport } from './routes/_onboarding/cardio-equipment'
import { Route as OnboardingAgeSelectImport } from './routes/_onboarding/age-select'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRouteRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingWorkoutRoute = OnboardingWorkoutImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingWeightSelectRoute = OnboardingWeightSelectImport.update({
  id: '/weight-select',
  path: '/weight-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingTimeSelectorRoute = OnboardingTimeSelectorImport.update({
  id: '/time-selector',
  path: '/time-selector',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingStrengthEquipmentRoute =
  OnboardingStrengthEquipmentImport.update({
    id: '/strength-equipment',
    path: '/strength-equipment',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)

const OnboardingSettingsRoute = OnboardingSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingNotificationsRoute = OnboardingNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingGoalsRoute = OnboardingGoalsImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingGenderSelectRoute = OnboardingGenderSelectImport.update({
  id: '/gender-select',
  path: '/gender-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingFitnessSelectRoute = OnboardingFitnessSelectImport.update({
  id: '/fitness-select',
  path: '/fitness-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingDayTimeRoute = OnboardingDayTimeImport.update({
  id: '/day-time',
  path: '/day-time',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingCardioEquipmentRoute = OnboardingCardioEquipmentImport.update({
  id: '/cardio-equipment',
  path: '/cardio-equipment',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingAgeSelectRoute = OnboardingAgeSelectImport.update({
  id: '/age-select',
  path: '/age-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_onboarding/age-select': {
      id: '/_onboarding/age-select'
      path: '/age-select'
      fullPath: '/age-select'
      preLoaderRoute: typeof OnboardingAgeSelectImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/cardio-equipment': {
      id: '/_onboarding/cardio-equipment'
      path: '/cardio-equipment'
      fullPath: '/cardio-equipment'
      preLoaderRoute: typeof OnboardingCardioEquipmentImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/day-time': {
      id: '/_onboarding/day-time'
      path: '/day-time'
      fullPath: '/day-time'
      preLoaderRoute: typeof OnboardingDayTimeImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/fitness-select': {
      id: '/_onboarding/fitness-select'
      path: '/fitness-select'
      fullPath: '/fitness-select'
      preLoaderRoute: typeof OnboardingFitnessSelectImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/gender-select': {
      id: '/_onboarding/gender-select'
      path: '/gender-select'
      fullPath: '/gender-select'
      preLoaderRoute: typeof OnboardingGenderSelectImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/goals': {
      id: '/_onboarding/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof OnboardingGoalsImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/notifications': {
      id: '/_onboarding/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof OnboardingNotificationsImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/settings': {
      id: '/_onboarding/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OnboardingSettingsImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/strength-equipment': {
      id: '/_onboarding/strength-equipment'
      path: '/strength-equipment'
      fullPath: '/strength-equipment'
      preLoaderRoute: typeof OnboardingStrengthEquipmentImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/time-selector': {
      id: '/_onboarding/time-selector'
      path: '/time-selector'
      fullPath: '/time-selector'
      preLoaderRoute: typeof OnboardingTimeSelectorImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/weight-select': {
      id: '/_onboarding/weight-select'
      path: '/weight-select'
      fullPath: '/weight-select'
      preLoaderRoute: typeof OnboardingWeightSelectImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/workout': {
      id: '/_onboarding/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof OnboardingWorkoutImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_onboarding/': {
      id: '/_onboarding/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof OnboardingRouteImport
    }
  }
}

// Create and export the route tree

interface OnboardingRouteRouteChildren {
  OnboardingAgeSelectRoute: typeof OnboardingAgeSelectRoute
  OnboardingCardioEquipmentRoute: typeof OnboardingCardioEquipmentRoute
  OnboardingDayTimeRoute: typeof OnboardingDayTimeRoute
  OnboardingFitnessSelectRoute: typeof OnboardingFitnessSelectRoute
  OnboardingGenderSelectRoute: typeof OnboardingGenderSelectRoute
  OnboardingGoalsRoute: typeof OnboardingGoalsRoute
  OnboardingNotificationsRoute: typeof OnboardingNotificationsRoute
  OnboardingSettingsRoute: typeof OnboardingSettingsRoute
  OnboardingStrengthEquipmentRoute: typeof OnboardingStrengthEquipmentRoute
  OnboardingTimeSelectorRoute: typeof OnboardingTimeSelectorRoute
  OnboardingWeightSelectRoute: typeof OnboardingWeightSelectRoute
  OnboardingWorkoutRoute: typeof OnboardingWorkoutRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAgeSelectRoute: OnboardingAgeSelectRoute,
  OnboardingCardioEquipmentRoute: OnboardingCardioEquipmentRoute,
  OnboardingDayTimeRoute: OnboardingDayTimeRoute,
  OnboardingFitnessSelectRoute: OnboardingFitnessSelectRoute,
  OnboardingGenderSelectRoute: OnboardingGenderSelectRoute,
  OnboardingGoalsRoute: OnboardingGoalsRoute,
  OnboardingNotificationsRoute: OnboardingNotificationsRoute,
  OnboardingSettingsRoute: OnboardingSettingsRoute,
  OnboardingStrengthEquipmentRoute: OnboardingStrengthEquipmentRoute,
  OnboardingTimeSelectorRoute: OnboardingTimeSelectorRoute,
  OnboardingWeightSelectRoute: OnboardingWeightSelectRoute,
  OnboardingWorkoutRoute: OnboardingWorkoutRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof OnboardingRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/age-select': typeof OnboardingAgeSelectRoute
  '/cardio-equipment': typeof OnboardingCardioEquipmentRoute
  '/day-time': typeof OnboardingDayTimeRoute
  '/fitness-select': typeof OnboardingFitnessSelectRoute
  '/gender-select': typeof OnboardingGenderSelectRoute
  '/goals': typeof OnboardingGoalsRoute
  '/notifications': typeof OnboardingNotificationsRoute
  '/settings': typeof OnboardingSettingsRoute
  '/strength-equipment': typeof OnboardingStrengthEquipmentRoute
  '/time-selector': typeof OnboardingTimeSelectorRoute
  '/weight-select': typeof OnboardingWeightSelectRoute
  '/workout': typeof OnboardingWorkoutRoute
  '/': typeof OnboardingIndexRoute
}

export interface FileRoutesByTo {
  '/signup': typeof SignupRoute
  '/age-select': typeof OnboardingAgeSelectRoute
  '/cardio-equipment': typeof OnboardingCardioEquipmentRoute
  '/day-time': typeof OnboardingDayTimeRoute
  '/fitness-select': typeof OnboardingFitnessSelectRoute
  '/gender-select': typeof OnboardingGenderSelectRoute
  '/goals': typeof OnboardingGoalsRoute
  '/notifications': typeof OnboardingNotificationsRoute
  '/settings': typeof OnboardingSettingsRoute
  '/strength-equipment': typeof OnboardingStrengthEquipmentRoute
  '/time-selector': typeof OnboardingTimeSelectorRoute
  '/weight-select': typeof OnboardingWeightSelectRoute
  '/workout': typeof OnboardingWorkoutRoute
  '/': typeof OnboardingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_onboarding/age-select': typeof OnboardingAgeSelectRoute
  '/_onboarding/cardio-equipment': typeof OnboardingCardioEquipmentRoute
  '/_onboarding/day-time': typeof OnboardingDayTimeRoute
  '/_onboarding/fitness-select': typeof OnboardingFitnessSelectRoute
  '/_onboarding/gender-select': typeof OnboardingGenderSelectRoute
  '/_onboarding/goals': typeof OnboardingGoalsRoute
  '/_onboarding/notifications': typeof OnboardingNotificationsRoute
  '/_onboarding/settings': typeof OnboardingSettingsRoute
  '/_onboarding/strength-equipment': typeof OnboardingStrengthEquipmentRoute
  '/_onboarding/time-selector': typeof OnboardingTimeSelectorRoute
  '/_onboarding/weight-select': typeof OnboardingWeightSelectRoute
  '/_onboarding/workout': typeof OnboardingWorkoutRoute
  '/_onboarding/': typeof OnboardingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/signup'
    | '/age-select'
    | '/cardio-equipment'
    | '/day-time'
    | '/fitness-select'
    | '/gender-select'
    | '/goals'
    | '/notifications'
    | '/settings'
    | '/strength-equipment'
    | '/time-selector'
    | '/weight-select'
    | '/workout'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signup'
    | '/age-select'
    | '/cardio-equipment'
    | '/day-time'
    | '/fitness-select'
    | '/gender-select'
    | '/goals'
    | '/notifications'
    | '/settings'
    | '/strength-equipment'
    | '/time-selector'
    | '/weight-select'
    | '/workout'
    | '/'
  id:
    | '__root__'
    | '/_onboarding'
    | '/signup'
    | '/_onboarding/age-select'
    | '/_onboarding/cardio-equipment'
    | '/_onboarding/day-time'
    | '/_onboarding/fitness-select'
    | '/_onboarding/gender-select'
    | '/_onboarding/goals'
    | '/_onboarding/notifications'
    | '/_onboarding/settings'
    | '/_onboarding/strength-equipment'
    | '/_onboarding/time-selector'
    | '/_onboarding/weight-select'
    | '/_onboarding/workout'
    | '/_onboarding/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_onboarding",
        "/signup"
      ]
    },
    "/_onboarding": {
      "filePath": "_onboarding/route.tsx",
      "children": [
        "/_onboarding/age-select",
        "/_onboarding/cardio-equipment",
        "/_onboarding/day-time",
        "/_onboarding/fitness-select",
        "/_onboarding/gender-select",
        "/_onboarding/goals",
        "/_onboarding/notifications",
        "/_onboarding/settings",
        "/_onboarding/strength-equipment",
        "/_onboarding/time-selector",
        "/_onboarding/weight-select",
        "/_onboarding/workout",
        "/_onboarding/"
      ]
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_onboarding/age-select": {
      "filePath": "_onboarding/age-select.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/cardio-equipment": {
      "filePath": "_onboarding/cardio-equipment.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/day-time": {
      "filePath": "_onboarding/day-time.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/fitness-select": {
      "filePath": "_onboarding/fitness-select.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/gender-select": {
      "filePath": "_onboarding/gender-select.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/goals": {
      "filePath": "_onboarding/goals.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/notifications": {
      "filePath": "_onboarding/notifications.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/settings": {
      "filePath": "_onboarding/settings.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/strength-equipment": {
      "filePath": "_onboarding/strength-equipment.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/time-selector": {
      "filePath": "_onboarding/time-selector.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/weight-select": {
      "filePath": "_onboarding/weight-select.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/workout": {
      "filePath": "_onboarding/workout.tsx",
      "parent": "/_onboarding"
    },
    "/_onboarding/": {
      "filePath": "_onboarding/index.tsx",
      "parent": "/_onboarding"
    }
  }
}
ROUTE_MANIFEST_END */
