/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteRouteImport } from './routes/_onboarding/route'
import { Route as RouteRouteImport } from './routes/_/route'
import { Route as OnboardingWorkoutRouteImport } from './routes/_onboarding/workout'
import { Route as OnboardingWeightSelectRouteImport } from './routes/_onboarding/weight-select'
import { Route as OnboardingTimeSelectorRouteImport } from './routes/_onboarding/time-selector'
import { Route as OnboardingStrengthEquipmentRouteImport } from './routes/_onboarding/strength-equipment'
import { Route as OnboardingSettingsRouteImport } from './routes/_onboarding/settings'
import { Route as OnboardingNotificationsRouteImport } from './routes/_onboarding/notifications'
import { Route as OnboardingGoalsRouteImport } from './routes/_onboarding/goals'
import { Route as OnboardingGenderSelectRouteImport } from './routes/_onboarding/gender-select'
import { Route as OnboardingFitnessSelectRouteImport } from './routes/_onboarding/fitness-select'
import { Route as OnboardingDayTimeRouteImport } from './routes/_onboarding/day-time'
import { Route as OnboardingCardioEquipmentRouteImport } from './routes/_onboarding/cardio-equipment'
import { Route as OnboardingAgeSelectRouteImport } from './routes/_onboarding/age-select'
import { Route as DashboardRouteImport } from './routes/_/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/_',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkoutRoute = OnboardingWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingWeightSelectRoute = OnboardingWeightSelectRouteImport.update({
  id: '/weight-select',
  path: '/weight-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingTimeSelectorRoute = OnboardingTimeSelectorRouteImport.update({
  id: '/time-selector',
  path: '/time-selector',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStrengthEquipmentRoute =
  OnboardingStrengthEquipmentRouteImport.update({
    id: '/strength-equipment',
    path: '/strength-equipment',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const OnboardingSettingsRoute = OnboardingSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingNotificationsRoute = OnboardingNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingGoalsRoute = OnboardingGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingGenderSelectRoute = OnboardingGenderSelectRouteImport.update({
  id: '/gender-select',
  path: '/gender-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingFitnessSelectRoute = OnboardingFitnessSelectRouteImport.update({
  id: '/fitness-select',
  path: '/fitness-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDayTimeRoute = OnboardingDayTimeRouteImport.update({
  id: '/day-time',
  path: '/day-time',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCardioEquipmentRoute =
  OnboardingCardioEquipmentRouteImport.update({
    id: '/cardio-equipment',
    path: '/cardio-equipment',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const OnboardingAgeSelectRoute = OnboardingAgeSelectRouteImport.update({
  id: '/age-select',
  path: '/age-select',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardRoute
  '/age-select': typeof OnboardingAgeSelectRoute
  '/cardio-equipment': typeof OnboardingCardioEquipmentRoute
  '/day-time': typeof OnboardingDayTimeRoute
  '/fitness-select': typeof OnboardingFitnessSelectRoute
  '/gender-select': typeof OnboardingGenderSelectRoute
  '/goals': typeof OnboardingGoalsRoute
  '/notifications': typeof OnboardingNotificationsRoute
  '/settings': typeof OnboardingSettingsRoute
  '/strength-equipment': typeof OnboardingStrengthEquipmentRoute
  '/time-selector': typeof OnboardingTimeSelectorRoute
  '/weight-select': typeof OnboardingWeightSelectRoute
  '/workout': typeof OnboardingWorkoutRoute
}
export interface FileRoutesByTo {
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardRoute
  '/age-select': typeof OnboardingAgeSelectRoute
  '/cardio-equipment': typeof OnboardingCardioEquipmentRoute
  '/day-time': typeof OnboardingDayTimeRoute
  '/fitness-select': typeof OnboardingFitnessSelectRoute
  '/gender-select': typeof OnboardingGenderSelectRoute
  '/goals': typeof OnboardingGoalsRoute
  '/notifications': typeof OnboardingNotificationsRoute
  '/settings': typeof OnboardingSettingsRoute
  '/strength-equipment': typeof OnboardingStrengthEquipmentRoute
  '/time-selector': typeof OnboardingTimeSelectorRoute
  '/weight-select': typeof OnboardingWeightSelectRoute
  '/workout': typeof OnboardingWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_': typeof RouteRouteWithChildren
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/signup': typeof SignupRoute
  '/_/dashboard': typeof DashboardRoute
  '/_onboarding/age-select': typeof OnboardingAgeSelectRoute
  '/_onboarding/cardio-equipment': typeof OnboardingCardioEquipmentRoute
  '/_onboarding/day-time': typeof OnboardingDayTimeRoute
  '/_onboarding/fitness-select': typeof OnboardingFitnessSelectRoute
  '/_onboarding/gender-select': typeof OnboardingGenderSelectRoute
  '/_onboarding/goals': typeof OnboardingGoalsRoute
  '/_onboarding/notifications': typeof OnboardingNotificationsRoute
  '/_onboarding/settings': typeof OnboardingSettingsRoute
  '/_onboarding/strength-equipment': typeof OnboardingStrengthEquipmentRoute
  '/_onboarding/time-selector': typeof OnboardingTimeSelectorRoute
  '/_onboarding/weight-select': typeof OnboardingWeightSelectRoute
  '/_onboarding/workout': typeof OnboardingWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signup'
    | '/dashboard'
    | '/age-select'
    | '/cardio-equipment'
    | '/day-time'
    | '/fitness-select'
    | '/gender-select'
    | '/goals'
    | '/notifications'
    | '/settings'
    | '/strength-equipment'
    | '/time-selector'
    | '/weight-select'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signup'
    | '/dashboard'
    | '/age-select'
    | '/cardio-equipment'
    | '/day-time'
    | '/fitness-select'
    | '/gender-select'
    | '/goals'
    | '/notifications'
    | '/settings'
    | '/strength-equipment'
    | '/time-selector'
    | '/weight-select'
    | '/workout'
  id:
    | '__root__'
    | '/_'
    | '/_onboarding'
    | '/signup'
    | '/_/dashboard'
    | '/_onboarding/age-select'
    | '/_onboarding/cardio-equipment'
    | '/_onboarding/day-time'
    | '/_onboarding/fitness-select'
    | '/_onboarding/gender-select'
    | '/_onboarding/goals'
    | '/_onboarding/notifications'
    | '/_onboarding/settings'
    | '/_onboarding/strength-equipment'
    | '/_onboarding/time-selector'
    | '/_onboarding/weight-select'
    | '/_onboarding/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_': {
      id: '/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/workout': {
      id: '/_onboarding/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof OnboardingWorkoutRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/weight-select': {
      id: '/_onboarding/weight-select'
      path: '/weight-select'
      fullPath: '/weight-select'
      preLoaderRoute: typeof OnboardingWeightSelectRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/time-selector': {
      id: '/_onboarding/time-selector'
      path: '/time-selector'
      fullPath: '/time-selector'
      preLoaderRoute: typeof OnboardingTimeSelectorRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/strength-equipment': {
      id: '/_onboarding/strength-equipment'
      path: '/strength-equipment'
      fullPath: '/strength-equipment'
      preLoaderRoute: typeof OnboardingStrengthEquipmentRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/settings': {
      id: '/_onboarding/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OnboardingSettingsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/notifications': {
      id: '/_onboarding/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof OnboardingNotificationsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/goals': {
      id: '/_onboarding/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof OnboardingGoalsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/gender-select': {
      id: '/_onboarding/gender-select'
      path: '/gender-select'
      fullPath: '/gender-select'
      preLoaderRoute: typeof OnboardingGenderSelectRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/fitness-select': {
      id: '/_onboarding/fitness-select'
      path: '/fitness-select'
      fullPath: '/fitness-select'
      preLoaderRoute: typeof OnboardingFitnessSelectRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/day-time': {
      id: '/_onboarding/day-time'
      path: '/day-time'
      fullPath: '/day-time'
      preLoaderRoute: typeof OnboardingDayTimeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/cardio-equipment': {
      id: '/_onboarding/cardio-equipment'
      path: '/cardio-equipment'
      fullPath: '/cardio-equipment'
      preLoaderRoute: typeof OnboardingCardioEquipmentRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_onboarding/age-select': {
      id: '/_onboarding/age-select'
      path: '/age-select'
      fullPath: '/age-select'
      preLoaderRoute: typeof OnboardingAgeSelectRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_/dashboard': {
      id: '/_/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof RouteRoute
    }
  }
}

interface RouteRouteChildren {
  DashboardRoute: typeof DashboardRoute
}

const RouteRouteChildren: RouteRouteChildren = {
  DashboardRoute: DashboardRoute,
}

const RouteRouteWithChildren = RouteRoute._addFileChildren(RouteRouteChildren)

interface OnboardingRouteRouteChildren {
  OnboardingAgeSelectRoute: typeof OnboardingAgeSelectRoute
  OnboardingCardioEquipmentRoute: typeof OnboardingCardioEquipmentRoute
  OnboardingDayTimeRoute: typeof OnboardingDayTimeRoute
  OnboardingFitnessSelectRoute: typeof OnboardingFitnessSelectRoute
  OnboardingGenderSelectRoute: typeof OnboardingGenderSelectRoute
  OnboardingGoalsRoute: typeof OnboardingGoalsRoute
  OnboardingNotificationsRoute: typeof OnboardingNotificationsRoute
  OnboardingSettingsRoute: typeof OnboardingSettingsRoute
  OnboardingStrengthEquipmentRoute: typeof OnboardingStrengthEquipmentRoute
  OnboardingTimeSelectorRoute: typeof OnboardingTimeSelectorRoute
  OnboardingWeightSelectRoute: typeof OnboardingWeightSelectRoute
  OnboardingWorkoutRoute: typeof OnboardingWorkoutRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingAgeSelectRoute: OnboardingAgeSelectRoute,
  OnboardingCardioEquipmentRoute: OnboardingCardioEquipmentRoute,
  OnboardingDayTimeRoute: OnboardingDayTimeRoute,
  OnboardingFitnessSelectRoute: OnboardingFitnessSelectRoute,
  OnboardingGenderSelectRoute: OnboardingGenderSelectRoute,
  OnboardingGoalsRoute: OnboardingGoalsRoute,
  OnboardingNotificationsRoute: OnboardingNotificationsRoute,
  OnboardingSettingsRoute: OnboardingSettingsRoute,
  OnboardingStrengthEquipmentRoute: OnboardingStrengthEquipmentRoute,
  OnboardingTimeSelectorRoute: OnboardingTimeSelectorRoute,
  OnboardingWeightSelectRoute: OnboardingWeightSelectRoute,
  OnboardingWorkoutRoute: OnboardingWorkoutRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
